version: '3'

services:
  nexus:
    image: sonatype/nexus3:latest
    ports:
      - "8082:8082"
    networks:
      - devops-network
    volumes:
      - nexus-data:/nexus-data

  mysql:
    image: mysql:latest
    networks:
      - devops-network
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=devops
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  devops-network:
    driver: bridge

volumes:
  nexus-data:
  mysql-data: